import type { Currency } from './currency';

/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  BASE DE DONNÉES TARIFAIRE DES OUTILS
 * ─────────────────────────────────────────────────────────────────────────────
 *  Règles appliquées à chaque ligne (et à toute ligne que vous ajouterez) :
 *
 *  1. Un prix est stocké UNE SEULE FOIS, dans la devise de facturation
 *     officielle de l'éditeur. Les montants USD / EUR / MAD / XAF affichés sont
 *     DÉRIVÉS (voir currency.ts).
 *  2. N'inventez jamais un prix. S'il n'est pas publié → model: 'contact-sales'.
 *  3. Tarif à la consommation → model: 'usage'. Au siège → model: 'per-user'.
 *  4. Une offre gratuite est un vrai prix (0 $) mais ses LIMITES doivent être
 *     indiquées.
 *  5. `source` doit être la page tarifaire de l'éditeur, et `verifiedOn` le jour
 *     de la vérification. `confidence: 'indicative'` marque un montant qui varie
 *     selon la région, le volume de contacts ou la négociation, et qui doit être
 *     revérifié avant d'être communiqué à un client.
 *
 *  Les éditeurs changent souvent leurs prix. Revérifiez avant chaque proposition.
 * ─────────────────────────────────────────────────────────────────────────────
 */
export type PricingModel =
  | 'free'
  | 'flat'
  | 'per-user'
  | 'usage'
  | 'contact-sales'
  | 'media-spend';

/** Les 8 postes de coût qui composent le coût total de possession (TCO). */
export type CostType =
  | 'software'
  | 'ai-subscription'
  | 'api'
  | 'automation'
  | 'advertising'
  | 'data'
  | 'implementation'
  | 'maintenance';

export type TierId = 'starter' | 'professional' | 'advanced';

export interface Tool {
  id: string;
  name: string;
  category: string;
  functionality: string;
  plan: string;
  model: PricingModel;
  costType: CostType;
  /** Devise de facturation officielle des montants ci-dessous. */
  currency: Currency;
  /** Prix officiel en facturation mensuelle. `null` s'il n'est pas publié. */
  monthly: number | null;
  /** Équivalent mensuel en facturation annuelle. `null` s'il n'y a pas d'offre annuelle. */
  annualMonthly: number | null;
  users: string;
  limits: string;
  variableCost?: string;
  apiCost?: string;
  extraCost?: string;
  tiers: TierId[];
  source: string;
  verifiedOn: string;
  confidence: 'verified' | 'indicative';
  note?: string;
}

const V = '2026-09-09';

export const TOOLS: Tool[] = [
  /* ── AI subscriptions ──────────────────────────────────────────────────── */
  {
    id: 'chatgpt-plus',
    name: 'ChatGPT Plus',
    category: 'IA',
    functionality: 'Stratégie, copywriting, analyse, idéation, GPTs personnalisés',
    plan: 'Plus',
    model: 'flat',
    costType: 'ai-subscription',
    currency: 'USD',
    monthly: 20,
    annualMonthly: null,
    users: '1 utilisateur',
    limits: 'Plan individuel. Quotas de messages sur les modèles les plus avancés.',
    apiCost: 'Non inclus — l’API est facturée séparément, au token.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://openai.com/chatgpt/pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'chatgpt-business',
    name: 'ChatGPT Business',
    category: 'IA',
    functionality: 'Espace équipe, GPTs partagés, console admin, données exclues de l’entraînement',
    plan: 'Business (ex-Team)',
    model: 'per-user',
    costType: 'ai-subscription',
    currency: 'USD',
    monthly: 30,
    annualMonthly: 25,
    users: 'Par utilisateur, minimum 2 sièges',
    limits: 'Quotas plus élevés que Plus. Les sièges Premium sont facturés à part.',
    extraCost: 'Sièges Premium : 125 $/utilisateur/mois en mensuel, 100 $/utilisateur/mois en annuel.',
    tiers: ['advanced'],
    source: 'https://openai.com/business/chatgpt-pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'claude-pro',
    name: 'Claude Pro',
    category: 'IA',
    functionality: 'Raisonnement long, briefs, analyse structurée, travail sur documents',
    plan: 'Pro',
    model: 'flat',
    costType: 'ai-subscription',
    currency: 'USD',
    monthly: 20,
    annualMonthly: 16.67,
    users: '1 utilisateur',
    limits: 'Quotas à l’usage. Les prix varient selon la région et hors taxes.',
    apiCost: 'Non inclus — l’API Anthropic est facturée séparément, au token.',
    tiers: ['professional', 'advanced'],
    source: 'https://claude.com/pricing',
    verifiedOn: V,
    confidence: 'verified',
    note: 'La facturation annuelle est de 200 $ d’avance (≈ 16,67 $/mois).',
  },
  {
    id: 'claude-team',
    name: 'Claude Team',
    category: 'IA',
    functionality: 'Projets partagés, collaboration, facturation centralisée',
    plan: 'Team — siège standard',
    model: 'per-user',
    costType: 'ai-subscription',
    currency: 'USD',
    monthly: 25,
    annualMonthly: 20,
    users: 'Par siège, minimum 2 membres',
    limits: 'Plus de quota que Pro. Les sièges Premium offrent environ 5× le quota standard.',
    extraCost: 'Sièges Premium : 125 $/siège/mois en mensuel, 100 $/siège/mois en annuel.',
    tiers: ['advanced'],
    source: 'https://claude.com/pricing',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'google-ai-pro',
    name: 'Google AI Pro (Gemini)',
    category: 'IA',
    functionality: 'Gemini dans Google Workspace, multimodal, recherche',
    plan: 'Google AI Pro',
    model: 'flat',
    costType: 'ai-subscription',
    currency: 'USD',
    monthly: 19.99,
    annualMonthly: null,
    users: '1 utilisateur',
    limits: 'Abonnement grand public, couplé au stockage Google One.',
    extraCost: 'Google AI Ultra se situe au-dessus, à un tarif mensuel supérieur.',
    tiers: ['professional', 'advanced'],
    source: 'https://gemini.google/subscriptions/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'llm-api',
    name: 'LLM APIs (OpenAI / Anthropic / Gemini)',
    category: 'IA',
    functionality: 'IA programmatique dans les automatisations : scoring, classification, génération',
    plan: 'À la consommation',
    model: 'usage',
    costType: 'api',
    currency: 'USD',
    monthly: null,
    annualMonthly: null,
    users: 'Illimité — facturé au token, pas au siège',
    limits: 'Pas de prix fixe. Coût = (tokens entrée + sortie) × tarif du modèle.',
    variableCost:
      'Fixez un plafond mensuel strict. Une automatisation marketing sobre se situe généralement à quelques dizaines de dollars par mois, pas des centaines.',
    apiCost: 'Par million de tokens entrée / sortie — les tarifs varient par modèle et changent souvent.',
    tiers: ['professional', 'advanced'],
    source: 'https://platform.openai.com/docs/pricing',
    verifiedOn: V,
    confidence: 'indicative',
    note: 'Tarification à l’usage — fixez toujours un plafond de dépense avant la mise en production.',
  },

  /* ── Automation ────────────────────────────────────────────────────────── */
  {
    id: 'make-free',
    name: 'Make',
    category: 'Automatisation',
    functionality: 'Constructeur visuel de scénarios reliant tous les outils de la stack',
    plan: 'Gratuit',
    model: 'free',
    costType: 'automation',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: '1 utilisateur',
    limits: '1 000 crédits/mois, intervalle de planification minimum de 15 minutes.',
    tiers: ['starter'],
    source: 'https://www.make.com/en/pricing',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'make-core',
    name: 'Make',
    category: 'Automatisation',
    functionality: 'Automatisations en production, scénarios actifs illimités',
    plan: 'Core',
    model: 'usage',
    costType: 'automation',
    currency: 'USD',
    monthly: 12,
    annualMonthly: 10.59,
    users: '1 utilisateur',
    limits: 'À partir de 10 000 crédits/mois. Le prix suit le pack de crédits.',
    variableCost: 'Chaque module qui traite une donnée consomme au moins un crédit.',
    tiers: ['professional'],
    source: 'https://www.make.com/en/pricing',
    verifiedOn: V,
    confidence: 'verified',
    note: 'Make est passé des « opérations » aux « crédits » comme unité de facturation en novembre 2025.',
  },
  {
    id: 'make-pro',
    name: 'Make',
    category: 'Automatisation',
    functionality: 'Exécution prioritaire, variables personnalisées, journal d’exécution complet',
    plan: 'Pro',
    model: 'usage',
    costType: 'automation',
    currency: 'USD',
    monthly: 21,
    annualMonthly: 18.82,
    users: '1 utilisateur',
    limits: 'Pack de crédits dimensionné selon votre volume.',
    tiers: ['advanced'],
    source: 'https://www.make.com/en/pricing',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'zapier-team',
    name: 'Zapier',
    category: 'Automatisation',
    functionality: 'Le plus large catalogue d’apps, le plus rapide pour des intégrations simples',
    plan: 'Team',
    model: 'usage',
    costType: 'automation',
    currency: 'USD',
    monthly: null,
    annualMonthly: 69,
    users: 'Jusqu’à 25 utilisateurs',
    limits: 'À partir de 2 000 tâches/mois ; dossiers partagés, rôles, SSO SAML.',
    variableCost: 'Les tâches au-delà du quota sont facturées à l’unité.',
    tiers: ['advanced'],
    source: 'https://zapier.com/pricing',
    verifiedOn: V,
    confidence: 'verified',
    note: 'Un plan gratuit (100 tâches/mois) et des paliers Professional moins chers existent.',
  },
  {
    id: 'n8n-self',
    name: 'n8n (self-hosted)',
    category: 'Automatisation',
    functionality: 'Maîtrisez votre couche d’automatisation — pas de facturation à l’exécution',
    plan: 'Édition Community',
    model: 'free',
    costType: 'automation',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Illimité',
    limits: 'Licence fair-code. Vous hébergez et maintenez le serveur vous-même.',
    extraCost: 'Hébergement : comptez environ 5 à 20 $/mois pour un petit VPS.',
    tiers: ['professional', 'advanced'],
    source: 'https://n8n.io/pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'n8n-cloud',
    name: 'n8n Cloud',
    category: 'Automatisation',
    functionality: 'n8n managé, facturé à l’exécution du workflow plutôt qu’à l’étape',
    plan: 'Starter / Pro',
    model: 'usage',
    costType: 'automation',
    currency: 'USD',
    monthly: null,
    annualMonthly: null,
    users: 'Utilisateurs et workflows illimités sur tous les plans',
    limits: 'Facturé aux exécutions mensuelles (un workflow complet = 1 exécution).',
    variableCost: 'Les plans incluent des crédits IA (≈2 300 sur Starter, 5 700+ sur Pro).',
    tiers: ['advanced'],
    source: 'https://n8n.io/pricing/',
    verifiedOn: V,
    confidence: 'indicative',
    note: 'Tarification à l’exécution — vérifiez la grille en vigueur avant de chiffrer.',
  },

  /* ── CRM ───────────────────────────────────────────────────────────────── */
  {
    id: 'hubspot-free',
    name: 'HubSpot CRM',
    category: 'CRM',
    functionality: 'Contacts, opportunités, pipelines, formulaires, liens de rendez-vous',
    plan: 'Outils gratuits',
    model: 'free',
    costType: 'software',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Utilisateurs gratuits illimités',
    limits: 'Marque HubSpot sur les formulaires et emails, pas de workflows d’automatisation.',
    tiers: ['starter'],
    source: 'https://www.hubspot.com/pricing/marketing',
    verifiedOn: V,
    confidence: 'verified',
    note: 'Le CRM gratuit est réellement exploitable — commencez ici, pas sur une offre payante.',
  },
  {
    id: 'hubspot-starter',
    name: 'HubSpot Marketing Hub',
    category: 'CRM',
    functionality: 'Email marketing, formulaires, automatisation simple, gestion publicitaire',
    plan: 'Starter',
    model: 'per-user',
    costType: 'software',
    currency: 'USD',
    monthly: 20,
    annualMonthly: 15,
    users: 'Par siège',
    limits: '1 000 contacts marketing inclus ; le prix augmente par paliers de contacts.',
    extraCost: 'Les contacts marketing supplémentaires sont facturés par blocs.',
    tiers: ['professional'],
    source: 'https://www.hubspot.com/pricing/marketing',
    verifiedOn: V,
    confidence: 'indicative',
  },
  {
    id: 'hubspot-pro',
    name: 'HubSpot Marketing Hub',
    category: 'CRM',
    functionality: 'Automatisation complète des workflows, lead scoring, campagnes, attribution',
    plan: 'Professional',
    model: 'flat',
    costType: 'software',
    currency: 'USD',
    monthly: 890,
    annualMonthly: 800,
    users: 'Sièges inclus, sièges supplémentaires facturés à part',
    limits: 'Paliers de contacts applicables. Onboarding payant obligatoire sur cette édition.',
    extraCost: 'Frais d’onboarding Professional ponctuels + tarif par siège supplémentaire.',
    tiers: ['advanced'],
    source: 'https://www.hubspot.com/pricing/marketing',
    verifiedOn: V,
    confidence: 'indicative',
    note: 'La plus grosse ligne de la plupart des stacks — à ne justifier que par le volume.',
  },

  /* ── Email ─────────────────────────────────────────────────────────────── */
  {
    id: 'brevo-free',
    name: 'Brevo',
    category: 'Email',
    functionality: 'Emails transactionnels et marketing, contacts, automatisation de base',
    plan: 'Gratuit',
    model: 'free',
    costType: 'software',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: '1 utilisateur',
    limits: 'Plafond d’envoi quotidien, logo Brevo sur les emails, contacts stockés illimités.',
    tiers: ['starter'],
    source: 'https://www.brevo.com/pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'brevo-starter',
    name: 'Brevo',
    category: 'Email',
    functionality: 'Tarification au volume — vous payez les envois, pas les contacts stockés',
    plan: 'Starter',
    model: 'usage',
    costType: 'software',
    currency: 'USD',
    monthly: 9,
    annualMonthly: null,
    users: '1 utilisateur (utilisateurs supplémentaires en option)',
    limits: 'À partir de 5 000 emails/mois ; le prix suit le palier de volume.',
    extraCost: 'Options : utilisateurs supplémentaires, IP dédiée, support téléphonique.',
    tiers: ['starter', 'professional'],
    source: 'https://www.brevo.com/pricing/',
    verifiedOn: V,
    confidence: 'verified',
    note: 'Le meilleur rapport prix/performance de cette stack pour le nurturing à faible volume.',
  },
  {
    id: 'brevo-business',
    name: 'Brevo',
    category: 'Email',
    functionality: 'Marketing automation, A/B testing, optimisation de l’heure d’envoi',
    plan: 'Business (Standard)',
    model: 'usage',
    costType: 'software',
    currency: 'USD',
    monthly: 18,
    annualMonthly: null,
    users: 'À partir de 3 utilisateurs',
    limits: 'Paliers de volume comme Starter ; limites d’automatisation levées.',
    tiers: ['professional', 'advanced'],
    source: 'https://www.brevo.com/pricing/',
    verifiedOn: V,
    confidence: 'indicative',
  },
  {
    id: 'mailchimp-essentials',
    name: 'Mailchimp',
    category: 'Email',
    functionality: 'Campagnes, parcours, templates, segmentation d’audience',
    plan: 'Essentials',
    model: 'usage',
    costType: 'software',
    currency: 'USD',
    monthly: 13,
    annualMonthly: null,
    users: '3 sièges',
    limits: 'À partir de 500 contacts. Le prix dépend du palier de contacts, pas des envois.',
    extraCost: 'Le dépassement du nombre de contacts fait passer automatiquement au palier supérieur.',
    tiers: ['starter'],
    source: 'https://mailchimp.com/pricing/marketing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'mailchimp-standard',
    name: 'Mailchimp',
    category: 'Email',
    functionality: 'Parcours avancés, retargeting, segmentation prédictive',
    plan: 'Standard',
    model: 'usage',
    costType: 'software',
    currency: 'USD',
    monthly: 20,
    annualMonthly: null,
    users: '5 sièges',
    limits: 'À partir de 500 contacts, puis tarification par palier de contacts.',
    tiers: ['professional'],
    source: 'https://mailchimp.com/pricing/marketing/',
    verifiedOn: V,
    confidence: 'verified',
    note: 'Recouvre presque totalement Brevo — choisissez l’un des deux, pas les deux.',
  },

  /* ── Social media ──────────────────────────────────────────────────────── */
  {
    id: 'meta-business-suite',
    name: 'Meta Business Suite',
    category: 'Réseaux sociaux',
    functionality: 'Publication, messagerie, statistiques pour Facebook et Instagram',
    plan: 'Gratuit',
    model: 'free',
    costType: 'software',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Par rôle, illimité',
    limits: 'Plateformes Meta uniquement. Pas de reporting multi-réseaux.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://business.facebook.com/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'metricool-free',
    name: 'Metricool',
    category: 'Réseaux sociaux',
    functionality: 'Planification et analytics multi-réseaux dans un seul calendrier',
    plan: 'Gratuit',
    model: 'free',
    costType: 'software',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: '1 utilisateur',
    limits: '1 marque, historique et publications programmées limités.',
    tiers: ['starter'],
    source: 'https://metricool.com/pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'metricool-starter',
    name: 'Metricool',
    category: 'Réseaux sociaux',
    functionality: 'Programmation multi-marques, veille concurrentielle, rapports en marque blanche',
    plan: 'Starter',
    model: 'flat',
    costType: 'software',
    currency: 'USD',
    monthly: 25,
    annualMonthly: 20,
    users: 'À partir de 1 utilisateur',
    limits: 'À partir de 5 marques ; le prix suit le nombre de marques.',
    extraCost: 'Advanced Analytics est une option payante.',
    tiers: ['professional'],
    source: 'https://metricool.com/pricing/',
    verifiedOn: V,
    confidence: 'indicative',
  },
  {
    id: 'metricool-advanced',
    name: 'Metricool',
    category: 'Réseaux sociaux',
    functionality: 'Reporting multi-marques et gestion des rôles, niveau agence',
    plan: 'Advanced',
    model: 'flat',
    costType: 'software',
    currency: 'USD',
    monthly: 67,
    annualMonthly: 53,
    users: 'Multi-utilisateurs',
    limits: 'À partir de 15 marques, puis paliers à 25 et 50 marques.',
    tiers: ['advanced'],
    source: 'https://metricool.com/pricing/',
    verifiedOn: V,
    confidence: 'indicative',
  },

  /* ── Design & creative ─────────────────────────────────────────────────── */
  {
    id: 'canva-free',
    name: 'Canva',
    category: 'Design',
    functionality: 'Production visuelle pour le social, les présentations et les créas publicitaires',
    plan: 'Gratuit',
    model: 'free',
    costType: 'software',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: '1 utilisateur',
    limits: 'Assets premium limités, pas de kit de marque, pas de détourage.',
    tiers: ['starter'],
    source: 'https://www.canva.com/pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'canva-business',
    name: 'Canva Business',
    category: 'Design',
    functionality: 'Kits de marque, redimensionnement, détourage, templates d’équipe, outils IA',
    plan: 'Business',
    model: 'per-user',
    costType: 'software',
    currency: 'USD',
    monthly: 20,
    annualMonthly: null,
    users: 'Par personne, sans minimum de sièges',
    limits: 'La génération IA est décomptée via un quota « AI Pass ».',
    extraCost: 'Les crédits AI Pass supplémentaires sont vendus séparément.',
    tiers: ['professional', 'advanced'],
    source: 'https://www.canva.com/pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'capcut',
    name: 'CapCut',
    category: 'Design',
    functionality: 'Montage vidéo court, sous-titres, templates',
    plan: 'Gratuit / Pro',
    model: 'free',
    costType: 'software',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: '1 utilisateur',
    limits: 'La version gratuite filigrane certains assets ; Pro débloque les effets premium et l’export.',
    extraCost: 'CapCut Pro est une mise à niveau payante — vérifiez le prix dans l’app pour votre région.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://www.capcut.com/',
    verifiedOn: V,
    confidence: 'indicative',
  },

  /* ── Advertising ───────────────────────────────────────────────────────── */
  {
    id: 'meta-ads',
    name: 'Meta Ads',
    category: 'Publicité',
    functionality: 'Acquisition payante sur Facebook et Instagram',
    plan: 'Enchères — budget média',
    model: 'media-spend',
    costType: 'advertising',
    currency: 'USD',
    monthly: null,
    annualMonthly: null,
    users: 'Accès par rôle, gratuit',
    limits: 'La plateforme elle-même est gratuite. Vous payez les impressions et les clics.',
    variableCost:
      'C’est un BUDGET MÉDIA, pas un abonnement logiciel. Ne fusionnez jamais les deux lignes dans un budget.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://www.facebook.com/business/ads',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'google-ads',
    name: 'Google Ads',
    category: 'Publicité',
    functionality: 'Acquisition Search, Performance Max, YouTube et Display',
    plan: 'Enchères — budget média',
    model: 'media-spend',
    costType: 'advertising',
    currency: 'USD',
    monthly: null,
    annualMonthly: null,
    users: 'Accès par rôle, gratuit',
    limits: 'Aucun coût de licence. Le coût par clic dépend de l’enchère et de votre quality score.',
    variableCost:
      'BUDGET MÉDIA. Suivez-le sur une ligne distincte du logiciel pour que le calcul de ROI reste honnête.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://ads.google.com/',
    verifiedOn: V,
    confidence: 'verified',
  },

  /* ── SEO ───────────────────────────────────────────────────────────────── */
  {
    id: 'gsc',
    name: 'Google Search Console',
    category: 'SEO',
    functionality: 'Données de requêtes réelles, indexation, Core Web Vitals, soumission du sitemap',
    plan: 'Gratuit',
    model: 'free',
    costType: 'data',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Illimité, selon les permissions',
    limits: '16 mois d’historique ; 1 000 lignes par export dans l’interface.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://search.google.com/search-console/about',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'semrush-pro',
    name: 'Semrush',
    category: 'SEO',
    functionality: 'Recherche de mots-clés, analyse concurrentielle, audit de site, suivi de position',
    plan: 'SEO Toolkit — Pro',
    model: 'flat',
    costType: 'software',
    currency: 'USD',
    monthly: 139,
    annualMonthly: 117.33,
    users: '1 utilisateur',
    limits: '5 projets, 500 mots-clés suivis, 10 000 résultats par rapport.',
    extraCost: 'Utilisateurs supplémentaires et modules additionnels (Local, AI Visibility) facturés à part.',
    tiers: ['professional'],
    source: 'https://www.semrush.com/pricing/seo/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'semrush-guru',
    name: 'Semrush',
    category: 'SEO',
    functionality: 'Boîte à outils contenu, historique, quotas élargis, connecteur Looker Studio',
    plan: 'SEO Toolkit — Guru',
    model: 'flat',
    costType: 'software',
    currency: 'USD',
    monthly: 249.95,
    annualMonthly: 248.17,
    users: '1 utilisateur',
    limits: '15 projets, 1 500 mots-clés suivis.',
    tiers: ['advanced'],
    source: 'https://www.semrush.com/pricing/seo/',
    verifiedOn: V,
    confidence: 'verified',
  },

  /* ── Analytics & data ──────────────────────────────────────────────────── */
  {
    id: 'ga4',
    name: 'Google Analytics 4',
    category: 'Analytics',
    functionality: 'Comportement, conversions, attribution, audiences',
    plan: 'Gratuit (standard)',
    model: 'free',
    costType: 'data',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Illimité, selon les permissions',
    limits: 'Limites de collecte et échantillonnage ; GA4 360 est tarifé pour l’entreprise.',
    extraCost: 'Analytics 360 : contacter le service commercial.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://marketingplatform.google.com/about/analytics/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'looker-studio',
    name: 'Looker Studio',
    category: 'Analytics',
    functionality: 'Dashboards marketing au-dessus de GA4, Ads, Sheets et du CRM',
    plan: 'Gratuit',
    model: 'free',
    costType: 'data',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Lecteurs illimités',
    limits: 'Certains connecteurs tiers sont payants ; Looker Studio Pro est une offre payante.',
    extraCost: 'Les connecteurs partenaires payants coûtent en général 10 à 50 $/mois par source.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://lookerstudio.google.com/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'power-bi-pro',
    name: 'Power BI Pro',
    category: 'Analytics',
    functionality: 'Modèles BI gouvernés, rafraîchissement planifié, partage dans toute l’organisation',
    plan: 'Pro',
    model: 'per-user',
    costType: 'data',
    currency: 'USD',
    monthly: 14,
    annualMonthly: null,
    users: 'Par utilisateur et par mois',
    limits: 'Le partage exige une licence pour chaque lecteur (en dessous de la capacité F64).',
    extraCost: 'La capacité Fabric F est facturée séparément via Azure.',
    tiers: ['advanced'],
    source: 'https://www.microsoft.com/en-us/power-platform/products/power-bi/pricing',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'sheets',
    name: 'Google Sheets / Excel',
    category: 'Analytics',
    functionality: 'Modélisation, suivi de budget, tableaux croisés rapides, transmission de données',
    plan: 'Gratuit / inclus dans Workspace ou Microsoft 365',
    model: 'free',
    costType: 'data',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Dépend de votre licence existante',
    limits: 'Versions personnelles gratuites ; l’usage professionnel est en général déjà inclus.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://workspace.google.com/pricing',
    verifiedOn: V,
    confidence: 'verified',
  },

  /* ── Infrastructure for this very site ─────────────────────────────────── */
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'Infrastructure',
    functionality: 'Base PostgreSQL qui stocke les leads capturés par cette page',
    plan: 'Gratuit / Pro',
    model: 'usage',
    costType: 'software',
    currency: 'USD',
    monthly: 25,
    annualMonthly: null,
    users: 'Utilisateurs API illimités',
    limits: 'Une offre gratuite généreuse suffit pour une landing page ; Pro démarre à 25 $/mois.',
    variableCost: 'Stockage, bande passante et calcul au-delà du quota du plan.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://supabase.com/pricing',
    verifiedOn: V,
    confidence: 'indicative',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'Infrastructure',
    functionality: 'Hébergement, CDN et routes API serverless de cette landing page',
    plan: 'Hobby / Pro',
    model: 'usage',
    costType: 'software',
    currency: 'USD',
    monthly: 20,
    annualMonthly: null,
    users: 'Par membre sur le plan Pro',
    limits: 'Hobby est gratuit pour un usage non commercial ; Pro coûte 20 $/membre/mois.',
    variableCost: 'Bande passante et exécution des fonctions au-delà du quota inclus.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://vercel.com/pricing',
    verifiedOn: V,
    confidence: 'indicative',
  },
];

/** Les 8 postes du TCO, dans l'ordre de présentation. */
export const COST_TYPES: {
  id: CostType;
  label: string;
  description: string;
}[] = [
  {
    id: 'software',
    label: '1 · Abonnement logiciel',
    description: 'Licences récurrentes : CRM, plateforme email, planificateur social, suite SEO.',
  },
  {
    id: 'ai-subscription',
    label: '2 · Abonnement IA',
    description: 'Sièges ChatGPT, Claude, Gemini utilisés par des humains au quotidien.',
  },
  {
    id: 'api',
    label: '3 · Coût API',
    description: 'Tokens consommés par l’IA à l’intérieur des automatisations. À l’usage, sans plafond par défaut.',
  },
  {
    id: 'automation',
    label: '4 · Coût d’automatisation',
    description: 'Make, Zapier ou n8n — facturés à l’opération, à la tâche ou à l’exécution.',
  },
  {
    id: 'advertising',
    label: '5 · Budget média publicitaire',
    description: 'Budget Meta Ads et Google Ads. C’est du média, PAS du logiciel. Ne fusionnez jamais les deux.',
  },
  {
    id: 'data',
    label: '6 · Coût data & analytics',
    description: 'GA4, Search Console, Looker Studio, licences Power BI et connecteurs.',
  },
  {
    id: 'implementation',
    label: '7 · Coût de mise en place',
    description: 'Conception et construction ponctuelles du système : architecture, workflows, migration.',
  },
  {
    id: 'maintenance',
    label: '8 · Coût de maintenance',
    description: 'Supervision, correction des scénarios cassés, entretien des prompts, itération. À budgéter systématiquement.',
  },
];

/** Quels outils se recouvrent, et ce qui peut être fusionné. Plus haut = plus remplaçable. */
export const REDUNDANCY: {
  group: string;
  overlap: string;
  score: number;
  verdict: string;
}[] = [
  {
    group: 'Brevo vs Mailchimp',
    overlap: 'Les deux sont des plateformes complètes d’email marketing et d’automatisation.',
    score: 90,
    verdict: 'Gardez-en un. Brevo est moins cher à faible volume de contacts, Mailchimp à faible volume d’envois.',
  },
  {
    group: 'Make vs Zapier vs n8n',
    overlap: 'Trois réponses à la même question : comment mes outils se parlent-ils ?',
    score: 85,
    verdict: 'Gardez-en un. Make pour la profondeur visuelle, Zapier pour la couverture, n8n pour maîtriser l’infrastructure.',
  },
  {
    group: 'HubSpot Marketing Pro vs (Brevo + Make)',
    overlap: 'Lead scoring, nurturing et workflows existent dans les deux configurations.',
    score: 70,
    verdict: 'En dessous de quelques milliers de contacts, Brevo + Make fait le travail pour une fraction du prix.',
  },
  {
    group: 'Metricool vs Meta Business Suite',
    overlap: 'Programmation et analytics pour les plateformes Meta.',
    score: 55,
    verdict: 'Meta Business Suite seul suffit si Facebook et Instagram sont vos seuls réseaux.',
  },
  {
    group: 'ChatGPT vs Claude vs Gemini',
    overlap: 'Des assistants généralistes aux capacités largement redondantes.',
    score: 45,
    verdict: 'Deux est un maximum raisonnable. Un troisième abonnement se rentabilise rarement.',
  },
  {
    group: 'Power BI vs Looker Studio',
    overlap: 'Dashboards et reporting sur les mêmes sources marketing.',
    score: 60,
    verdict: 'Looker Studio est gratuit et natif à GA4/Ads. Power BI justifie sa licence sur la gouvernance.',
  },
];
