import type { Currency } from './currency';

/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  TOOL PRICING DATABASE
 * ─────────────────────────────────────────────────────────────────────────────
 *  Rules applied to every row (and to every row you add later):
 *
 *  1. A price is stored ONCE, in the vendor's official billing currency.
 *     USD / EUR / MAD / XAF figures on the page are DERIVED (see currency.ts).
 *  2. Never invent a price. If it is not published →  model: 'contact-sales'.
 *  3. Consumption-based →  model: 'usage'.  Seat-based →  model: 'per-user'.
 *  4. A free tier is a real price ($0) but its LIMITS must be stated.
 *  5. `source` must be the vendor's own pricing page, and `verifiedOn` the day
 *     it was checked. `confidence: 'indicative'` marks a figure that varies by
 *     region, contact volume or negotiation and must be re-checked before it is
 *     quoted to a client.
 *
 *  Vendors change prices frequently. Re-verify before every proposal.
 * ─────────────────────────────────────────────────────────────────────────────
 */

export type PricingModel =
  | 'free'
  | 'flat'
  | 'per-user'
  | 'usage'
  | 'contact-sales'
  | 'media-spend';

/** The 8 cost buckets that together make up the Total Cost of Ownership. */
export type CostType =
  | 'software'
  | 'ai-subscription'
  | 'api'
  | 'automation'
  | 'advertising'
  | 'data'
  | 'implementation'
  | 'maintenance';

export type TierId = 'starter' | 'professional' | 'advanced';

export interface Tool {
  id: string;
  name: string;
  category: string;
  functionality: string;
  plan: string;
  model: PricingModel;
  costType: CostType;
  /** Official billing currency for the figures below. */
  currency: Currency;
  /** Official price when billed monthly. `null` when not publicly published. */
  monthly: number | null;
  /** Monthly equivalent when billed annually. `null` when there is no annual plan. */
  annualMonthly: number | null;
  users: string;
  limits: string;
  variableCost?: string;
  apiCost?: string;
  extraCost?: string;
  tiers: TierId[];
  source: string;
  verifiedOn: string;
  confidence: 'verified' | 'indicative';
  note?: string;
}

const V = '2026-09-09';

export const TOOLS: Tool[] = [
  /* ── AI subscriptions ──────────────────────────────────────────────────── */
  {
    id: 'chatgpt-plus',
    name: 'ChatGPT Plus',
    category: 'AI',
    functionality: 'Strategy, copywriting, analysis, ideation, custom GPTs',
    plan: 'Plus',
    model: 'flat',
    costType: 'ai-subscription',
    currency: 'USD',
    monthly: 20,
    annualMonthly: null,
    users: '1 user',
    limits: 'Individual plan. Message limits on the most advanced models.',
    apiCost: 'Not included — the API is billed separately per token.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://openai.com/chatgpt/pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'chatgpt-business',
    name: 'ChatGPT Business',
    category: 'AI',
    functionality: 'Team workspace, shared GPTs, admin console, data excluded from training',
    plan: 'Business (ex-Team)',
    model: 'per-user',
    costType: 'ai-subscription',
    currency: 'USD',
    monthly: 30,
    annualMonthly: 25,
    users: 'Per user, minimum 2 seats',
    limits: 'Higher message limits than Plus. Premium seats are priced separately.',
    extraCost: 'Premium seats: $125/user/month monthly, $100/user/month annually.',
    tiers: ['advanced'],
    source: 'https://openai.com/business/chatgpt-pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'claude-pro',
    name: 'Claude Pro',
    category: 'AI',
    functionality: 'Long-form reasoning, briefs, structured analysis, document work',
    plan: 'Pro',
    model: 'flat',
    costType: 'ai-subscription',
    currency: 'USD',
    monthly: 20,
    annualMonthly: 16.67,
    users: '1 user',
    limits: 'Usage-based rate limits. Prices vary by region and exclude tax.',
    apiCost: 'Not included — the Anthropic API is billed separately per token.',
    tiers: ['professional', 'advanced'],
    source: 'https://claude.com/pricing',
    verifiedOn: V,
    confidence: 'verified',
    note: 'Annual billing is $200 up front (≈ $16.67/month).',
  },
  {
    id: 'claude-team',
    name: 'Claude Team',
    category: 'AI',
    functionality: 'Shared projects, collaboration, central billing',
    plan: 'Team — standard seat',
    model: 'per-user',
    costType: 'ai-subscription',
    currency: 'USD',
    monthly: 25,
    annualMonthly: 20,
    users: 'Per seat, minimum 2 members',
    limits: 'More usage than Pro. Premium seats carry ~5× standard usage.',
    extraCost: 'Premium seats: $125/seat/month monthly, $100/seat/month annually.',
    tiers: ['advanced'],
    source: 'https://claude.com/pricing',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'google-ai-pro',
    name: 'Google AI Pro (Gemini)',
    category: 'AI',
    functionality: 'Gemini in the Google Workspace surface, multimodal, research',
    plan: 'Google AI Pro',
    model: 'flat',
    costType: 'ai-subscription',
    currency: 'USD',
    monthly: 19.99,
    annualMonthly: null,
    users: '1 user',
    limits: 'Consumer subscription bundled with Google One storage.',
    extraCost: 'Google AI Ultra sits above it at a higher monthly price.',
    tiers: ['professional', 'advanced'],
    source: 'https://gemini.google/subscriptions/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'llm-api',
    name: 'LLM APIs (OpenAI / Anthropic / Gemini)',
    category: 'AI',
    functionality: 'Programmatic AI inside automations: scoring, classification, generation',
    plan: 'Pay-as-you-go',
    model: 'usage',
    costType: 'api',
    currency: 'USD',
    monthly: null,
    annualMonthly: null,
    users: 'Unlimited — billed per token, not per seat',
    limits: 'No fixed price. Cost = (input + output tokens) × model rate.',
    variableCost:
      'Budget a hard monthly cap. A lean marketing automation typically lands in the tens of dollars per month, not hundreds.',
    apiCost: 'Per 1M input / output tokens — rates differ per model and change often.',
    tiers: ['professional', 'advanced'],
    source: 'https://platform.openai.com/docs/pricing',
    verifiedOn: V,
    confidence: 'indicative',
    note: 'Usage-based pricing — always set a spend limit before going live.',
  },

  /* ── Automation ────────────────────────────────────────────────────────── */
  {
    id: 'make-free',
    name: 'Make',
    category: 'Automation',
    functionality: 'Visual scenario builder connecting every tool in the stack',
    plan: 'Free',
    model: 'free',
    costType: 'automation',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: '1 user',
    limits: '1,000 credits/month, 15-minute minimum scheduling interval.',
    tiers: ['starter'],
    source: 'https://www.make.com/en/pricing',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'make-core',
    name: 'Make',
    category: 'Automation',
    functionality: 'Production automations, unlimited active scenarios',
    plan: 'Core',
    model: 'usage',
    costType: 'automation',
    currency: 'USD',
    monthly: 12,
    annualMonthly: 10.59,
    users: '1 user',
    limits: 'From 10,000 credits/month. Price scales with the credit pack.',
    variableCost: 'Each module that processes data consumes at least one credit.',
    tiers: ['professional'],
    source: 'https://www.make.com/en/pricing',
    verifiedOn: V,
    confidence: 'verified',
    note: 'Make moved from "operations" to "credits" as the billing unit in Nov 2025.',
  },
  {
    id: 'make-pro',
    name: 'Make',
    category: 'Automation',
    functionality: 'Priority execution, custom variables, full-text execution log',
    plan: 'Pro',
    model: 'usage',
    costType: 'automation',
    currency: 'USD',
    monthly: 21,
    annualMonthly: 18.82,
    users: '1 user',
    limits: 'Credit pack sized to your volume.',
    tiers: ['advanced'],
    source: 'https://www.make.com/en/pricing',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'zapier-team',
    name: 'Zapier',
    category: 'Automation',
    functionality: 'Widest app catalogue, fastest to ship simple integrations',
    plan: 'Team',
    model: 'usage',
    costType: 'automation',
    currency: 'USD',
    monthly: null,
    annualMonthly: 69,
    users: 'Up to 25 users',
    limits: 'From 2,000 tasks/month; shared folders, roles, SAML SSO.',
    variableCost: 'Extra tasks are billed pay-per-task above the plan allowance.',
    tiers: ['advanced'],
    source: 'https://zapier.com/pricing',
    verifiedOn: V,
    confidence: 'verified',
    note: 'A Free plan (100 tasks/month) and cheaper Professional tiers exist.',
  },
  {
    id: 'n8n-self',
    name: 'n8n (self-hosted)',
    category: 'Automation',
    functionality: 'Own your automation layer — no per-execution billing',
    plan: 'Community Edition',
    model: 'free',
    costType: 'automation',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Unlimited',
    limits: 'Fair-code licence. You run and maintain the server yourself.',
    extraCost: 'Hosting: budget roughly $5–$20/month for a small VPS.',
    tiers: ['professional', 'advanced'],
    source: 'https://n8n.io/pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'n8n-cloud',
    name: 'n8n Cloud',
    category: 'Automation',
    functionality: 'Managed n8n, billed per workflow execution rather than per step',
    plan: 'Starter / Pro',
    model: 'usage',
    costType: 'automation',
    currency: 'USD',
    monthly: null,
    annualMonthly: null,
    users: 'Unlimited users and workflows on every plan',
    limits: 'Priced by monthly executions (a full workflow run = 1 execution).',
    variableCost: 'Plans bundle AI credits (≈2,300 on Starter, 5,700+ on Pro).',
    tiers: ['advanced'],
    source: 'https://n8n.io/pricing/',
    verifiedOn: V,
    confidence: 'indicative',
    note: 'Execution-based pricing — check the current tier grid before quoting.',
  },

  /* ── CRM ───────────────────────────────────────────────────────────────── */
  {
    id: 'hubspot-free',
    name: 'HubSpot CRM',
    category: 'CRM',
    functionality: 'Contacts, deals, pipelines, forms, meeting links',
    plan: 'Free Tools',
    model: 'free',
    costType: 'software',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Unlimited free users',
    limits: 'HubSpot branding on forms/emails, no automation workflows.',
    tiers: ['starter'],
    source: 'https://www.hubspot.com/pricing/marketing',
    verifiedOn: V,
    confidence: 'verified',
    note: 'The free CRM is genuinely usable — start here, not on a paid tier.',
  },
  {
    id: 'hubspot-starter',
    name: 'HubSpot Marketing Hub',
    category: 'CRM',
    functionality: 'Email marketing, forms, simple automation, ad management',
    plan: 'Starter',
    model: 'per-user',
    costType: 'software',
    currency: 'USD',
    monthly: 20,
    annualMonthly: 15,
    users: 'Per seat',
    limits: '1,000 marketing contacts included; price rises with contact tiers.',
    extraCost: 'Additional marketing contacts are billed in blocks.',
    tiers: ['professional'],
    source: 'https://www.hubspot.com/pricing/marketing',
    verifiedOn: V,
    confidence: 'indicative',
  },
  {
    id: 'hubspot-pro',
    name: 'HubSpot Marketing Hub',
    category: 'CRM',
    functionality: 'Full workflow automation, lead scoring, campaigns, attribution',
    plan: 'Professional',
    model: 'flat',
    costType: 'software',
    currency: 'USD',
    monthly: 890,
    annualMonthly: 800,
    users: 'Seats included, extra seats billed separately',
    limits: 'Contact tiers apply. Mandatory paid onboarding on this edition.',
    extraCost: 'One-off Professional onboarding fee + per-extra-seat pricing.',
    tiers: ['advanced'],
    source: 'https://www.hubspot.com/pricing/marketing',
    verifiedOn: V,
    confidence: 'indicative',
    note: 'The single biggest line item in most stacks — only justify it with volume.',
  },

  /* ── Email ─────────────────────────────────────────────────────────────── */
  {
    id: 'brevo-free',
    name: 'Brevo',
    category: 'Email',
    functionality: 'Transactional + marketing email, contacts, basic automation',
    plan: 'Free',
    model: 'free',
    costType: 'software',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: '1 user',
    limits: 'Daily sending cap, Brevo logo on emails, unlimited contacts stored.',
    tiers: ['starter'],
    source: 'https://www.brevo.com/pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'brevo-starter',
    name: 'Brevo',
    category: 'Email',
    functionality: 'Volume-priced email — you pay for sends, not for contacts stored',
    plan: 'Starter',
    model: 'usage',
    costType: 'software',
    currency: 'USD',
    monthly: 9,
    annualMonthly: null,
    users: '1 user (extra users are an add-on)',
    limits: 'From 5,000 emails/month; price scales with the email volume tier.',
    extraCost: 'Add-ons: extra users, dedicated IP, phone support.',
    tiers: ['starter', 'professional'],
    source: 'https://www.brevo.com/pricing/',
    verifiedOn: V,
    confidence: 'verified',
    note: 'Best price/performance in this stack for lead nurturing at low volume.',
  },
  {
    id: 'brevo-business',
    name: 'Brevo',
    category: 'Email',
    functionality: 'Marketing automation, A/B testing, send-time optimisation',
    plan: 'Business (Standard)',
    model: 'usage',
    costType: 'software',
    currency: 'USD',
    monthly: 18,
    annualMonthly: null,
    users: 'From 3 users',
    limits: 'Volume-tiered like Starter; automation limits lifted.',
    tiers: ['professional', 'advanced'],
    source: 'https://www.brevo.com/pricing/',
    verifiedOn: V,
    confidence: 'indicative',
  },
  {
    id: 'mailchimp-essentials',
    name: 'Mailchimp',
    category: 'Email',
    functionality: 'Campaigns, journeys, templates, audience segmentation',
    plan: 'Essentials',
    model: 'usage',
    costType: 'software',
    currency: 'USD',
    monthly: 13,
    annualMonthly: null,
    users: '3 seats',
    limits: 'From 500 contacts. Price is driven by the contact tier, not by sends.',
    extraCost: 'Contact overage moves you up a tier automatically.',
    tiers: ['starter'],
    source: 'https://mailchimp.com/pricing/marketing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'mailchimp-standard',
    name: 'Mailchimp',
    category: 'Email',
    functionality: 'Advanced journeys, retargeting, predictive segmentation',
    plan: 'Standard',
    model: 'usage',
    costType: 'software',
    currency: 'USD',
    monthly: 20,
    annualMonthly: null,
    users: '5 seats',
    limits: 'From 500 contacts, then contact-tier pricing.',
    tiers: ['professional'],
    source: 'https://mailchimp.com/pricing/marketing/',
    verifiedOn: V,
    confidence: 'verified',
    note: 'Overlaps almost completely with Brevo — pick one, not both.',
  },

  /* ── Social media ──────────────────────────────────────────────────────── */
  {
    id: 'meta-business-suite',
    name: 'Meta Business Suite',
    category: 'Social Media',
    functionality: 'Publishing, inbox, page insights for Facebook & Instagram',
    plan: 'Free',
    model: 'free',
    costType: 'software',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Role-based, unlimited',
    limits: 'Meta platforms only. No cross-network reporting.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://business.facebook.com/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'metricool-free',
    name: 'Metricool',
    category: 'Social Media',
    functionality: 'Cross-network planning and analytics in one calendar',
    plan: 'Free',
    model: 'free',
    costType: 'software',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: '1 user',
    limits: '1 brand, limited history and scheduled posts.',
    tiers: ['starter'],
    source: 'https://metricool.com/pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'metricool-starter',
    name: 'Metricool',
    category: 'Social Media',
    functionality: 'Multi-brand scheduling, competitor tracking, white-label reports',
    plan: 'Starter',
    model: 'flat',
    costType: 'software',
    currency: 'USD',
    monthly: 25,
    annualMonthly: 20,
    users: 'From 1 user',
    limits: 'From 5 brands; price scales with the number of brands.',
    extraCost: 'Advanced Analytics is a paid add-on.',
    tiers: ['professional'],
    source: 'https://metricool.com/pricing/',
    verifiedOn: V,
    confidence: 'indicative',
  },
  {
    id: 'metricool-advanced',
    name: 'Metricool',
    category: 'Social Media',
    functionality: 'Agency-grade multi-brand reporting and roles',
    plan: 'Advanced',
    model: 'flat',
    costType: 'software',
    currency: 'USD',
    monthly: 67,
    annualMonthly: 53,
    users: 'Multi-user',
    limits: 'From 15 brands, scaling to 25 and 50 brand tiers.',
    tiers: ['advanced'],
    source: 'https://metricool.com/pricing/',
    verifiedOn: V,
    confidence: 'indicative',
  },

  /* ── Design & creative ─────────────────────────────────────────────────── */
  {
    id: 'canva-free',
    name: 'Canva',
    category: 'Design',
    functionality: 'Visual production for social, decks and ad creative',
    plan: 'Free',
    model: 'free',
    costType: 'software',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: '1 user',
    limits: 'Limited premium assets, no brand kit, no background remover.',
    tiers: ['starter'],
    source: 'https://www.canva.com/pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'canva-business',
    name: 'Canva Business',
    category: 'Design',
    functionality: 'Brand kits, resize, background remover, team templates, AI tools',
    plan: 'Business',
    model: 'per-user',
    costType: 'software',
    currency: 'USD',
    monthly: 20,
    annualMonthly: null,
    users: 'Per person, no seat minimum',
    limits: 'AI generation is metered by an "AI Pass" allowance.',
    extraCost: 'Additional AI Pass credits are sold separately.',
    tiers: ['professional', 'advanced'],
    source: 'https://www.canva.com/pricing/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'capcut',
    name: 'CapCut',
    category: 'Design',
    functionality: 'Short-form video editing, captions, templates',
    plan: 'Free / Pro',
    model: 'free',
    costType: 'software',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: '1 user',
    limits: 'Free tier watermarks some assets; Pro unlocks premium effects & export.',
    extraCost: 'CapCut Pro is a paid upgrade — check the in-app price for your region.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://www.capcut.com/',
    verifiedOn: V,
    confidence: 'indicative',
  },

  /* ── Advertising ───────────────────────────────────────────────────────── */
  {
    id: 'meta-ads',
    name: 'Meta Ads',
    category: 'Advertising',
    functionality: 'Paid acquisition on Facebook & Instagram',
    plan: 'Auction — media spend',
    model: 'media-spend',
    costType: 'advertising',
    currency: 'USD',
    monthly: null,
    annualMonthly: null,
    users: 'Role-based access, free',
    limits: 'The platform itself is free. You pay for impressions and clicks.',
    variableCost:
      'This is MEDIA BUDGET, not a software subscription. Never merge the two lines in a budget.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://www.facebook.com/business/ads',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'google-ads',
    name: 'Google Ads',
    category: 'Advertising',
    functionality: 'Search, Performance Max, YouTube and Display acquisition',
    plan: 'Auction — media spend',
    model: 'media-spend',
    costType: 'advertising',
    currency: 'USD',
    monthly: null,
    annualMonthly: null,
    users: 'Role-based access, free',
    limits: 'No licence fee. Cost per click is set by the auction and your quality score.',
    variableCost:
      'MEDIA BUDGET. Track it as a separate line from software so your ROI maths stays honest.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://ads.google.com/',
    verifiedOn: V,
    confidence: 'verified',
  },

  /* ── SEO ───────────────────────────────────────────────────────────────── */
  {
    id: 'gsc',
    name: 'Google Search Console',
    category: 'SEO',
    functionality: 'Real query data, indexing, Core Web Vitals, sitemap submission',
    plan: 'Free',
    model: 'free',
    costType: 'data',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Unlimited, permission-based',
    limits: '16 months of history; 1,000 rows per export in the UI.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://search.google.com/search-console/about',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'semrush-pro',
    name: 'Semrush',
    category: 'SEO',
    functionality: 'Keyword research, competitor analysis, site audit, rank tracking',
    plan: 'SEO Toolkit — Pro',
    model: 'flat',
    costType: 'software',
    currency: 'USD',
    monthly: 139,
    annualMonthly: 117.33,
    users: '1 user',
    limits: '5 projects, 500 keywords tracked, 10k results per report.',
    extraCost: 'Extra users and add-on toolkits (Local, AI Visibility) are billed separately.',
    tiers: ['professional'],
    source: 'https://www.semrush.com/pricing/seo/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'semrush-guru',
    name: 'Semrush',
    category: 'SEO',
    functionality: 'Content toolkit, historical data, larger limits, Looker Studio connector',
    plan: 'SEO Toolkit — Guru',
    model: 'flat',
    costType: 'software',
    currency: 'USD',
    monthly: 249.95,
    annualMonthly: 248.17,
    users: '1 user',
    limits: '15 projects, 1,500 keywords tracked.',
    tiers: ['advanced'],
    source: 'https://www.semrush.com/pricing/seo/',
    verifiedOn: V,
    confidence: 'verified',
  },

  /* ── Analytics & data ──────────────────────────────────────────────────── */
  {
    id: 'ga4',
    name: 'Google Analytics 4',
    category: 'Analytics',
    functionality: 'Behaviour, conversions, attribution, audiences',
    plan: 'Free (standard)',
    model: 'free',
    costType: 'data',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Unlimited, permission-based',
    limits: 'Data-collection limits and sampling; GA4 360 is enterprise-priced.',
    extraCost: 'Analytics 360: contact sales.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://marketingplatform.google.com/about/analytics/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'looker-studio',
    name: 'Looker Studio',
    category: 'Analytics',
    functionality: 'Marketing dashboards on top of GA4, Ads, Sheets and the CRM',
    plan: 'Free',
    model: 'free',
    costType: 'data',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Unlimited viewers',
    limits: 'Some third-party connectors are paid; Looker Studio Pro is a paid tier.',
    extraCost: 'Paid partner connectors typically run $10–$50/month per source.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://lookerstudio.google.com/',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'power-bi-pro',
    name: 'Power BI Pro',
    category: 'Analytics',
    functionality: 'Governed BI models, scheduled refresh, sharing across the org',
    plan: 'Pro',
    model: 'per-user',
    costType: 'data',
    currency: 'USD',
    monthly: 14,
    annualMonthly: null,
    users: 'Per user, per month',
    limits: 'Sharing requires every viewer to hold a licence (below F64 capacity).',
    extraCost: 'Fabric F-capacity is billed separately through Azure.',
    tiers: ['advanced'],
    source: 'https://www.microsoft.com/en-us/power-platform/products/power-bi/pricing',
    verifiedOn: V,
    confidence: 'verified',
  },
  {
    id: 'sheets',
    name: 'Google Sheets / Excel',
    category: 'Analytics',
    functionality: 'Modelling, budget tracking, quick pivots, data hand-off',
    plan: 'Free / bundled with Workspace or Microsoft 365',
    model: 'free',
    costType: 'data',
    currency: 'USD',
    monthly: 0,
    annualMonthly: 0,
    users: 'Depends on your existing licence',
    limits: 'Free personal tiers; business use normally already bundled.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://workspace.google.com/pricing',
    verifiedOn: V,
    confidence: 'verified',
  },

  /* ── Infrastructure for this very site ─────────────────────────────────── */
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'Infrastructure',
    functionality: 'PostgreSQL database storing the leads captured by this page',
    plan: 'Free / Pro',
    model: 'usage',
    costType: 'software',
    currency: 'USD',
    monthly: 25,
    annualMonthly: null,
    users: 'Unlimited API users',
    limits: 'A generous free tier covers a landing page; Pro starts at $25/month.',
    variableCost: 'Storage, bandwidth and compute add-ons above the plan quota.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://supabase.com/pricing',
    verifiedOn: V,
    confidence: 'indicative',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'Infrastructure',
    functionality: 'Hosting, CDN and serverless API routes for this landing page',
    plan: 'Hobby / Pro',
    model: 'usage',
    costType: 'software',
    currency: 'USD',
    monthly: 20,
    annualMonthly: null,
    users: 'Per member on Pro',
    limits: 'Hobby is free for non-commercial use; Pro is $20/member/month.',
    variableCost: 'Bandwidth and function execution above the included quota.',
    tiers: ['starter', 'professional', 'advanced'],
    source: 'https://vercel.com/pricing',
    verifiedOn: V,
    confidence: 'indicative',
  },
];

/** The 8 TCO buckets, in the order they are presented. */
export const COST_TYPES: {
  id: CostType;
  label: string;
  description: string;
}[] = [
  {
    id: 'software',
    label: '1 · Software subscription',
    description: 'Recurring licences: CRM, email platform, social scheduler, SEO suite.',
  },
  {
    id: 'ai-subscription',
    label: '2 · AI subscription',
    description: 'ChatGPT, Claude, Gemini seats used by humans in day-to-day work.',
  },
  {
    id: 'api',
    label: '3 · API cost',
    description: 'Tokens consumed by AI running inside automations. Usage-based, uncapped by default.',
  },
  {
    id: 'automation',
    label: '4 · Automation cost',
    description: 'Make, Zapier or n8n — priced per operation, task or execution.',
  },
  {
    id: 'advertising',
    label: '5 · Advertising media spend',
    description: 'Meta Ads and Google Ads budget. This is media, NOT software. Never merge the two.',
  },
  {
    id: 'data',
    label: '6 · Data & analytics cost',
    description: 'GA4, Search Console, Looker Studio, Power BI licences and connectors.',
  },
  {
    id: 'implementation',
    label: '7 · Implementation cost',
    description: 'One-off design and build of the system: architecture, workflows, migration.',
  },
  {
    id: 'maintenance',
    label: '8 · Maintenance cost',
    description: 'Monitoring, fixing broken scenarios, prompt upkeep, iteration. Always budget it.',
  },
];

/** Which tools overlap, and what can be collapsed. Higher = more replaceable. */
export const REDUNDANCY: {
  group: string;
  overlap: string;
  score: number;
  verdict: string;
}[] = [
  {
    group: 'Brevo vs Mailchimp',
    overlap: 'Both are full email marketing + automation platforms.',
    score: 90,
    verdict: 'Keep one. Brevo is cheaper at low contact volume, Mailchimp at low send volume.',
  },
  {
    group: 'Make vs Zapier vs n8n',
    overlap: 'Three answers to the same question: how do my tools talk to each other?',
    score: 85,
    verdict: 'Keep one. Make for visual depth, Zapier for breadth, n8n to own the infrastructure.',
  },
  {
    group: 'HubSpot Marketing Pro vs (Brevo + Make)',
    overlap: 'Lead scoring, nurturing and workflows exist in both setups.',
    score: 70,
    verdict: 'Below a few thousand contacts, Brevo + Make does the job for a fraction of the cost.',
  },
  {
    group: 'Metricool vs Meta Business Suite',
    overlap: 'Scheduling and analytics for Meta platforms.',
    score: 55,
    verdict: 'Meta Business Suite alone is enough if Facebook and Instagram are your only networks.',
  },
  {
    group: 'ChatGPT vs Claude vs Gemini',
    overlap: 'General-purpose assistants with heavily overlapping capabilities.',
    score: 45,
    verdict: 'Two is a reasonable maximum. A third seat rarely pays for itself.',
  },
  {
    group: 'Power BI vs Looker Studio',
    overlap: 'Dashboards and reporting on the same marketing sources.',
    score: 60,
    verdict: 'Looker Studio is free and native to GA4/Ads. Power BI earns its licence on governance.',
  },
];
